# Generated by Django 3.2.8 on 2021-10-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(default=None, max_length=100)),
                ('answer1', models.TextField(default=None, max_length=600)),
                ('img1', models.ImageField(upload_to='img')),
                ('question2', models.CharField(default=None, max_length=100)),
                ('answer2', models.TextField(default=None, max_length=600)),
                ('img2', models.ImageField(upload_to='img')),
            ],
        ),
    ]
