# Generated by Django 3.2.8 on 2021-12-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithohome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='renting_form_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.BigIntegerField(default='', max_length=100)),
                ('add', models.CharField(default='', max_length=100)),
                ('approval', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(default='', max_length=100)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('fat', models.CharField(choices=[('belly', 'BELLY'), ('thigh', 'THIGH'), ('legs', 'LEGS'), ('back', 'BACK'), ('arms', 'ARMS')], max_length=100)),
                ('build', models.CharField(choices=[('belly', 'BELLY'), ('thigh', 'THIGH'), ('legs', 'LEGS'), ('back', 'BACK'), ('arms', 'ARMS')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='answer1',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='answer2',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='img1',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='img2',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='question1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='question2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
