# Generated by Django 3.2.8 on 2021-12-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithohome', '0002_auto_20211206_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting_form_data',
            name='approval',
            field=models.CharField(default='', max_length=10),
        ),
    ]
