# Generated by Django 3.2.8 on 2021-11-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithohome', '0002_auto_20211113_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='fat',
            field=models.CharField(default='', max_length=100),
        ),
    ]
