# Generated by Django 3.2.8 on 2021-12-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithohome', '0003_alter_renting_form_data_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting_form_data',
            name='approval',
            field=models.CharField(default='', max_length=100),
        ),
    ]
