# Generated by Django 3.2.8 on 2021-11-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithohome', '0004_alter_userdata_fat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='build',
            field=models.CharField(choices=[('belly', 'BELLY'), ('thigh', 'THIGH'), ('legs', 'LEGS'), ('back', 'BACK'), ('arms', 'ARMS')], max_length=100),
        ),
    ]
