# Generated by Django 3.2.8 on 2021-12-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fithohome', '0009_approval_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='approval_data',
        ),
        migrations.AddField(
            model_name='renting_form_data',
            name='approval',
            field=models.BooleanField(default=True),
        ),
    ]
